name: Schedule Trigger All Providers

on:
  schedule:
    - cron: '0 12 * * *'   # every day at 12 am
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/azure.yml/dispatches \
            -d '{"ref":"main"}'
            
      - name: AWS
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/aws.yml/dispatches \
            -d '{"ref":"main"}'

      - name: GCP
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/gcp.yml/dispatches \
            -d '{"ref":"main"}'

            
      - name: GCP Multiple Configurations
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/gcpMulti.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Github
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/git.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Kubernetes
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/kube.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Kubernetes Multiple Configurations
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/kubeMulti.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Helm
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/helm.yml/dispatches \
            -d '{"ref":"main"}'

      - name: HTTP
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/http.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Office 365
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/o365.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Google Workspace
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workspace.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Google Workspace Multiple
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workspaceMulti.yml/dispatches \
            -d '{"ref":"main"}'
